### ISSUE TITLE
Спробуйте наступні тести

### ISSUE THREAD

**Issue by KostushkoIA** [EedSan/JavaLaboratory#3]
10,AU,,Australia має видати 2 + 2 + 0 + 9
11,AU,"",Aus""tralia має видати 2 + 2 + 0 + 11

**Comment by EedSan** [comment]
Не совсем понимаю почему во втором примере ответ 2+2+0+11 мне казалось должно быть 2+2+0+10. Ведь по заданию в файле:"Лабораторна робота 1 java.docx" парсер такие кавычки схолпывает в 1 символ

И по поводу всей проблемы, я просто не правильно трактовал задание и добавил в класс Counter filter(integer -> integer>0) из-за которого пропали все эти нули.

**Comment by EedSan** [comment]
> 10,AU,,Australia має видати 2 + 2 + 0 + 9
> 11,AU,"",Aus""tralia має видати 2 + 2 + 0 + 11

Не совсем понимаю почему во втором примере ответ 2+2+0+11 мне казалось должно быть 2+2+0+10. Ведь по заданию в файле:"Лабораторна робота 1 java.docx" парсер такие кавычки схолпывает в 1 символ

И по поводу всей проблемы, я просто не правильно трактовал задание и добавил в класс Counter filter(integer -> integer>0) из-за которого пропали все эти нули.
